name: Update Blocklist

on:
  schedule:
    # 每天 UTC 02:00 (菲律宾/北京时间 10:00) 运行
    - cron: '0 0 * * *'
  # 允许当你修改了 targets.txt 后自动触发更新
  push:
    paths:
      - 'targets_sites.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须给写权限才能提交代码
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Run generator
        run: python generate.py
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add blocklist.txt
          # 如果文件没变化，就不提交，避免产生空的 commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update blocklist" && git push)
